---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: hello-app
spec:
  encryptedData:
    .dockerconfigjson: AgAmNnvhbmgslzEGFcjb2kDDv7/1BTsNaPdTe600m2DJzRuALCIaLs6hGTwZ3BAN1J9t9ApxJXMHegLc6onIYYoOyzcdNZRui/qflTBI8CaYae2oKeA9l4Y0NoVP9N6tGpumenuQU6JKJNkSKNwB4V46Woc7pkBok3GeDMcDX336vMqRhfen7rENTKDGd0nkz59mwfiWBse/g2UWH33+6ckCpiN0O+EJiUtfgEE4og9EIwPKp4v6es03mbnxSXsLTj2Dd1XK3edfd0xwUxqtRhuFxxmVEChh6u8zU65iy2920iYBU05Uv2H0flEL1jNFxsILoPxMhz7nya6mrJj95n7E1yGH+AGBrWyLdYiwq0yVRbKEbEG0Z9lNJVEfvnVGa7N7FOZQ3Y9WjJbss3cxWLFSa6IHGbu8s4REe/+irbshlLlSlga5qX5rlPgZpnFuNxc+vMhwMkJpaqZlYlnKZz3AONwOvApj/8YlnzTYPB6apXjvH16LY6QOhC1N4zfkgSNghFNagqb6ZUt6Ec3VsVsdAZJwzxhBBMagIfthXZAT5rZg24fmwGxA4B6wk87Wrla7P6J1kCgY0yOMz9S7VEBB8chJ4smQutMmVT93Gge+IzL2iLyA9lKiyaT2BGnAYiAxrrvaT6+9hABgg6HBxHmn6jPVmvLR/ChUs81mvHTRDvgOxSHVStFO7HxAvFsE2m63khibTFGpcGymm6PQAl/JtKoCMfz2KSTuxLG1sghmg/xOzPTruof6+j6UqfIO5uBdPz44C5v7+kxNY1yjcnVt5u5Snx9O7U7B/zNshXsPre7gDOUlOWm1bvFB06k9ybr2R78Q3X5+1QrCNoSM5w9zfqEBTS0O7UI1FysrvRsnwK8tK79WXab9VFUvMFh9gzvEj/2zHPiThIizHeCjOm2Wd5GH2EDoaGHNVXlOplvjOaom
  template:
    metadata:
      name: ghcr-pull
      namespace: hello-app
    type: kubernetes.io/dockerconfigjson
